export const WORLD_CUP_TEAMS = [
  "Algeria",
  "Argentina",
  "Australia",
  "Austria",
  "Belgium",
  "Bosnia and Herzegovina",
  "Brazil",
  "Cabo Verde",
  "Canada",
  "Colombia",
  "Congo DR",
  "Cote d'Ivoire",
  "Croatia",
  "Curacao",
  "Czechia",
  "Ecuador",
  "Egypt",
  "England",
  "France",
  "Germany",
  "Ghana",
  "Haiti",
  "IR Iran",
  "Iraq",
  "Japan",
  "Jordan",
  "Korea Republic",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Panama",
  "Paraguay",
  "Portugal",
  "Qatar",
  "Saudi Arabia",
  "Scotland",
  "Senegal",
  "South Africa",
  "Spain",
  "Sweden",
  "Switzerland",
  "Tunisia",
  "Turkiye",
  "USA",
  "Uruguay",
  "Uzbekistan",
] as const;

const TEAM_API_SEARCH_NAMES: Record<string, string> = {
  USA: "United States",
  Turkiye: "Turkey",
  "IR Iran": "Iran",
  "Korea Republic": "South Korea",
  "Cote d'Ivoire": "Ivory Coast",
  "Congo DR": "DR Congo",
  Czechia: "Czech Republic",
};

export function getTeamApiSearchName(teamName: string) {
  return TEAM_API_SEARCH_NAMES[teamName] ?? teamName;
}
